framework:
    messenger:
        transports:
            sync: 'sync://'
        routing:
            'App\Backoffice\Application\Command\CreateMeasurement\CreateMeasurementCommand': 'sync'
            'App\Backoffice\Application\Command\CreateSensor\CreateSensorCommand': 'sync'
