# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Backoffice\Infrastructure\Controller\:
        resource: '../src/Backoffice/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    App\Backoffice\Domain\Repository\WineRepository: '@App\Backoffice\Infrastructure\Persistence\Doctrine\Repository\WineDoctrineRepository'
    App\Backoffice\Domain\Repository\SensorRepository: '@App\Backoffice\Infrastructure\Persistence\Doctrine\Repository\SensorDoctrineRepository'
    App\Backoffice\Domain\Repository\MeasurementRepository: '@App\Backoffice\Infrastructure\Persistence\Doctrine\Repository\MeasurementDoctrineRepository'

    App\Backoffice\Application\Command\CreateMeasurement\CreateMeasurementCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Backoffice\Application\Command\CreateSensor\CreateSensorCommandHandler:
        tags: [ 'messenger.message_handler' ]
        
    App\Backoffice\Application\Query\GetWines\GetWinesQueryHandler:
        tags: ['messenger.message_handler']
    
    App\Backoffice\Application\Query\GetSensors\GetSensorsQueryHandler:
        tags: ['messenger.message_handler']

    App\Shared\Infrastructure\Listener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher: '@security.password_hasher'
